# Generated by Django 3.2.9 on 2021-11-17 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211118_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AlterField(
            model_name='donors',
            name='mobile_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
