# Generated by Django 3.2.9 on 2021-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211118_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='choices',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-')], default='A+', max_length=9),
        ),
    ]
