# Generated by Django 3.2.9 on 2021-11-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_donors_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='choices',
            new_name='BLOOD_GROUP',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='documentId',
            new_name='Document_ID',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='fullname',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='pincode',
            new_name='Pincode',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='donors',
            name='Mobile_Number',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
