# Generated by Django 3.2.9 on 2021-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211118_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='BLOOD_GROUP',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=9),
        ),
    ]
